Cleanup old oplfex devices
noironetworks/aci-containers pull request #951
Opened 2022-02-02 12:38 UTC by akhilamohanan

* Check if there are any other opflex-odevs in the list which have a
different “fabricPathDn” than the last one
* Flag these entries for delete after a configurable period which defaults to 30 minutes
* Just before finally deleting the entry check if the opflex-odev list has changed and if the opflex-odevs we are trying to delete are not the only ones in the list or are currently being used

2022-02-03 19:16 UTC, snaiksat requested changes

2022-02-03 19:16 UTC, snaiksat commented on pkg/controller/services.go
> +						devices = append(devices[:i], devices[i+1:]...)
I am not sure I understand the logic here, aren't you iterating over "devices"? So, if L308 is true, it means you found a candidate device to delete? And if so, should you not make note of that device in a temporary list and set a flag "update" to True. L310 would not be required. Outside this for loop you check if the temporary list in not empty, and if so iterate through this temp list to delete the devices for this node (and if deleted add this node to the nodeUpdates list).

2022-02-04 08:42 UTC, snaiksat commented on pkg/controller/config.go
> +	DeviceDeleteTimeout float64 `json:"device-delete-timeout,omitempty"`
per comment in acc-provision patch, please rename to opflex-device-delete-timeout

2022-02-04 08:43 UTC, snaiksat commented
minor comment about renaming the config, other than that looks good...

2022-02-04 10:25 UTC, akhilamohanan commented on pkg/controller/config.go
> +	DeviceDeleteTimeout float64 `json:"device-delete-timeout,omitempty"`
addressed

2022-02-04 10:38 UTC, akhilamohanan commented
Tested vm migration after applying the following patch to the PR:


diff --git a/pkg/controller/controller.go b/pkg/controller/controller.go
index 8659b9bdd..c7c0adce1 100644
--- a/pkg/controller/controller.go
+++ b/pkg/controller/controller.go
@@ -496,7 +496,7 @@ func (cont *AciController) Run(stopCh <-chan struct{}) {
 
        // If OpflexDeviceDeleteTimeout is not defined, default to 1800s
        if cont.config.OpflexDeviceDeleteTimeout == 0 {
-               cont.config.OpflexDeviceDeleteTimeout = 1800
+               cont.config.OpflexDeviceDeleteTimeout = 2
        }
 
        // If not defined, default to 32
diff --git a/pkg/controller/services.go b/pkg/controller/services.go
index 321c97e33..21e8da913 100644
--- a/pkg/controller/services.go
+++ b/pkg/controller/services.go
@@ -1112,6 +1112,7 @@ func (cont *AciController) postOpflexDeviceDelete(nodes []string) {
 }
 
 func (cont *AciController) opflexDeviceDeleted(dn string) {
+       return
        var nodeUpdates []string
        var dnFound bool //to check if the dn belongs to this cluster
        cont.indexMutex.Lock()

2022-02-04 20:26 UTC, snaiksat approved these changes

2022-02-04 20:26 UTC, merged